[default_con]
uri = "http://sportsdata.misports.cn/beitai/nbaapi"
data = '''
        {
        "customer":"hupu",
        "key":"hupu",
        "encrypted":"2d05623b53f432ea0d514eecda45ac61",
        "random":"1"
        }
        '''
header = '''
        {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "zh-CN,zh;q=0.9",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4503.0 Safari/537.36"
        }
        '''

# 球队列表
[teamlist]
router = "/team/list"

# 球员列表
[playerlist]
router = "/player/list"

# 自由球员列表
[freeagents]
router = "/player/freeagents"

# 指定球员赛季数据
[getplayerstats]
router = "/statistics/getplayerstats"